# 异常捕获

## 基本介绍

当使用 restframework 进行前后端分离开发时，若后端出现异常。则前端请求数据的返回结果并不一定是 JSON 格式数据，它可能会直接返回一个 HTML 文档（Django 大黄页）。

这显然对前端开发人员非常不友好，所以我们需要把它处理掉。

## 源码阅读

接下来我们从源码角度刨析 restframework 内部是如何处理异常的。

首先在 APIView 中的 dispath 方法中有关于异常的捕获，它的异常捕获是从执行认证开始直到封装返回对象结束。

源码如下：

```
def dispatch(self, request, *args, **kwargs):

    self.args = args
    self.kwargs = kwargs
    request = self.initialize_request(request, *args, **kwargs)
    self.request = request
    self.headers = self.default_response_header

    # 开始捕获异常
    try:
        self.initial(request, *args, **kwargs)

        # Get the appropriate handler method
        if request.method.lower() in self.http_method_names:
            handler = getattr(self, request.method.lower(),
                              self.http_method_not_allowed)
        else:
            handler = self.http_method_not_allowed

        response = handler(request, *args, **kwargs)

    except Exception as exc:
        # 若发生异常，则执行这里
        response = self.handle_exception(exc)

    self.response = self.finalize_response(request, response, *args, **kwargs)
    return self.response
```

接下来可以看看 handle_exception 方法：

```
def handle_exception(self, exc):

    # 判断该异常是不是 AuthenticationFailed 的实例
    # 如果是它会进行一些默认处理
    if isinstance(exc, (exceptions.NotAuthenticated,
                        exceptions.AuthenticationFailed)):
        # WWW-Authenticate header for 401 responses, else coerce to 403
        auth_header = self.get_authenticate_header(self.request)

        if auth_header:
            exc.auth_header = auth_header
        else:
            exc.status_code = status.HTTP_403_FORBIDDEN

    exception_handler = self.get_exception_handler()

    context = self.get_exception_handler_context()

    # 这里是核心代码，它会查找你是否则 在settings.py 中定义了
    # 异常处理程序，其实内部代码就是
    # return self.settings.EXCEPTION_HANDLER
    # 如果没有定义，它默认会使用
    # from rest_framework.views import exception_handler
    # 来处理异常
    response = exception_handler(exc, context)

    # 如果上面的代码返回结果是 None，则代表该异常不是由 DRF 引起
    # 那么它会交给 Django 处理，所以最后会返回一个大黄页
    if response is None:
        self.raise_uncaught_exception(exc)

    response.exception = True
    return response
```

restframework 能够处理的异常都在 exception_handler 方法中定义了，如下所示：

```
def exception_handler(exc, context):
    if isinstance(exc, Http404):
        exc = exceptions.NotFound()
    elif isinstance(exc, PermissionDenied):
        exc = exceptions.PermissionDenied()

    if isinstance(exc, exceptions.APIException):
        headers = {}
        if getattr(exc, 'auth_header', None):
            headers['WWW-Authenticate'] = exc.auth_header
        if getattr(exc, 'wait', None):
            headers['Retry-After'] = '%d' % exc.wait

        if isinstance(exc.detail, (list, dict)):
            data = exc.detail
        else:
            data = {'detail': exc.detail}

        set_rollback()
        return Response(data, status=exc.status_code, headers=headers)
        # 上面都是 DRF 可以处理的异常

    return None
```

## 自定义异常

通过源码阅读我们可以发现，若 DRF 发现了自己处理不了的异常时（exception_handler 返回 None），那么它会将这个异常交给 Django 来处理，所以最后会返回大黄页。

我们需要做的其实就是在异常发生时通过我们自己定义的异常处理程序替换掉 内置的 exception_handler 异常处理程序，让它最后不返回 None 即可。

### 全局配置

首先，在异常发生时，第一步就是来运行我们自己定义的异常捕获程序。

需要在 settings.py 中配置：

```
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "app01.aberrant.exception_catch"
}
```

### 书写异常

接下来在 app01 目录中新建 aberrant.py 文件，并书写以下代码：

```
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import exception_handler


def exception_catch(exc, context):
    # 做一个切面，先运行它内置的异常处理程序
    # 如果返回 None，我们就把它拦截了
    result = exception_handler(exc, context)

    if result is None:
        # 如果返回是 None，则返回未知错误和错误详情
        # 并返回 503 状态码代表服务器无法使用，
        # 只要保证非 None 即可
        return Response(
            data=f"Unknown error, error details : {str(exc)}",
            status=status.HTTP_503_SERVICE_UNAVAILABLE,
        )

    return result
```

### 代码测试

我们自己伪造一个异常，查看最后返回结果：

```
from rest_framework.views import APIView


class Example(APIView):
    def get(self, *args, **kwargs):
        raise Exception("Test ...")
```

编写路由映射：

```
from django.contrib import admin
from django.urls import path

from app01 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', views.Example.as_view())
]
```

GET 方式访问 http://127.0.0.1:8000/test/，最终结果如下：

```
Unknown error, error details : Test ...
```
